{
 "title": "Agent Monitoring",
 "tags": [
  "agent",
  "vector"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "host", "label": "Host", "query": { "query": "label_values(host)" } },
   { "name": "pid", "label": "Pid", "query": { "query": "label_values(pid)" } },
   { "name": "component_id", "label": "Component id", "query": { "query": "label_values(component_id)" } },
   { "name": "component_type", "label": "Component type", "query": { "query": "label_values(component_type)" } },
   { "name": "component_kind", "label": "Component kind", "query": { "query": "label_values(component_kind)" } }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component errors rate",
   "type": "timeseries",
   "description": "The rate of errors encountered by this component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(vector_component_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Component discarded events rate",
   "type": "timeseries",
   "description": "The rate of events dropped by this component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vector_component_discarded_events_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Dropped logs ($__interval)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({application=\"dead-letter-queue\", host=\"$host\"} | json [$__interval]))",
     "legendFormat": "{{metadata_dropped_component_id}}"
    }
   ]
  },
  {
   "title": "Dropped logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "{application=\"dead-letter-queue\", host=\"$host\"} | json"
    }
   ]
  },
  {
   "title": "Vector errors ($__interval)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({application=\"vector\", host=\"$host\", pid=\"$pid\"} | json | metadata_level = `ERROR` [$__interval]))",
     "legendFormat": "{{metadata_dropped_component_id}}"
    }
   ]
  },
  {
   "title": "Vector Logs (ERROR)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "{application=\"vector\", host=\"$host\", pid=\"$pid\"} | json | metadata_level = `ERROR`"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "The total number of seconds the Vector instance has been up.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "vector_uptime_seconds{host =~ \"$host\", job =~ \"$job\"}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vector_utilization { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }"
    }
   ]
  },
  {
   "title": "Internal metrics cardinality",
   "type": "timeseries",
   "description": "The total number of metrics emitted from the internal metrics registry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "vector_internal_metrics_cardinality"
    }
   ]
  },
  { "title": "Component sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Component sent events rate",
   "type": "timeseries",
   "description": "The rate of events emitted by this component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Component sent event bytes rate",
   "type": "timeseries",
   "description": "The rate of event bytes emitted by this component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_event_bytes_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Component sent bytes rate",
   "type": "timeseries",
   "description": "The rate of raw bytes sent by this component to destination sinks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  { "title": "Component received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Component received events count",
   "type": "timeseries",
   "description": "A histogram of the number of events passed in each internal batch in Vector’s internal topology.\n\nNote that this is separate than sink-level batching. It is mostly useful for low level debugging performance issues in Vector due to small internal batches.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "vector_component_received_events_count_count{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }"
    }
   ]
  },
  {
   "title": "Component received event bytes rate",
   "type": "timeseries",
   "description": "The rate of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(vector_component_received_event_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Component received bytes rate",
   "type": "timeseries",
   "description": "The rate of raw bytes accepted by this component from source origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(vector_component_received_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Component received events rate",
   "type": "timeseries",
   "description": "The rate of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(vector_component_received_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  { "title": "Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Sent events rate",
   "type": "timeseries",
   "description": "The rate of events sent by this buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "rate(vector_buffer_sent_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Byte size",
   "type": "timeseries",
   "description": "The number of bytes current in the buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "vector_buffer_byte_size { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }"
    }
   ]
  },
  {
   "title": "Received events rate",
   "type": "timeseries",
   "description": "The rate of events received by this buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "rate(vector_buffer_received_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "The number of events currently in the buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "vector_buffer_events { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }"
    }
   ]
  },
  { "title": "Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Added rate",
   "type": "timeseries",
   "description": "The rate of files Vector has found to watch.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "rate(vector_files_added_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Resumed rate",
   "type": "timeseries",
   "description": "The rate of times Vector has resumed watching a file.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "rate(vector_files_resumed_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Checkpoints total",
   "type": "timeseries",
   "description": "The total number of files checkpointed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    { "expr": "vector_checkpoints_total" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Client responses rate",
   "type": "timeseries",
   "description": "The rate of HTTP requests, tagged with the response code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "rate(vector_http_client_responses_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])"
    }
   ]
  }
 ]
}