{
 "title": "Monotonicity",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Default query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Graphite",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "target": "stats.foo" }
     ]
    },
    {
     "title": "Prometheus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      { "expr": "foo_requests_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Graphite like", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Graphite",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    { "target": "stats.foo" }
   ]
  },
  {
   "title": "Prometheus (like statsd + graphite)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(foo_requests_total[10s]) OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graphite integral like", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Graphite integral",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "target": "integral(stats.foo)" }
   ]
  },
  {
   "title": "Prometheus (like graphite)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(foo_requests_total[10s])*10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}