{
 "title": "JVM (Micrometer Top 10)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [
  "otlp",
  "push"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(jvm_info,service_name)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(jvm_info,deployment_environment)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used{service_name=\"$service_name\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used{service_name=\"$service_name\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})*100/sum by (service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"})*100/sum by(service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_start_time{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by(service_instance_id) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", status=~\"5..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (rate(http_server_requests_sum{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", status!~\"5..\"}[1m]))/sum by (service_instance_id) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", status!~\"5..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, tomcat_threads_busy{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.tomcat.busy"
    },
    {
     "expr": "topk(10, tomcat_threads_current{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.tomcat.current"
    },
    {
     "expr": "topk(10, tomcat_threads_config_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.tomcat.max"
    },
    {
     "expr": "topk(10, jetty_threads_busy{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.jetty.busy"
    },
    {
     "expr": "topk(10, jetty_threads_current{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.jetty.current"
    },
    {
     "expr": "topk(10, jetty_threads_config_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.jetty.max"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}))",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_committed{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}))",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}))",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"}))",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, sum(jvm_memory_committed{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", instance=\"$instance\", area=\"nonheap\"}))",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "topk(10, sum(jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", instance=\"$instance\", area=\"nonheap\"}))",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}))",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_committed{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}))",
     "legendFormat": "{{instance}}.committed"
    },
    {
     "expr": "topk(10, sum(jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}))",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, system_cpu_usage{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.system"
    },
    {
     "expr": "topk(10, process_cpu_usage{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.process"
    },
    {
     "expr": "topk(10, avg_over_time(process_cpu_usage{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1h]))",
     "legendFormat": "{{instance}}.process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, system_load_average_1m{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.system-1m"
    },
    {
     "expr": "topk(10, system_cpu_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, jvm_threads_live{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.live"
    },
    {
     "expr": "topk(10, jvm_threads_daemon{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.daemon"
    },
    {
     "expr": "topk(10, jvm_threads_peak{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.peak"
    },
    {
     "expr": "topk(10, process_threads{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, jvm_threads_states{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}..{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "topk(10, increase(logback_events{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, process_files_open{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.open"
    },
    {
     "expr": "topk(10, process_files_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, jvm_memory_committed{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{instance}}.commited"
    },
    {
     "expr": "topk(10, jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, jvm_memory_committed{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "{{instance}}.commited"
    },
    {
     "expr": "topk(10, jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "{{instance}}.max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, rate(jvm_gc_pause_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, rate(jvm_gc_pause_sum{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m])/rate(jvm_gc_pause_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.avg {{action}} ({{cause}})"
    },
    {
     "expr": "topk(10, jvm_gc_pause_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, rate(jvm_gc_memory_allocated{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.allocated"
    },
    {
     "expr": "topk(10, rate(jvm_gc_memory_promoted{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, jvm_classes_loaded{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
     "legendFormat": "{{instance}}.loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, delta(jvm_classes_loaded{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))",
     "legendFormat": "{{instance}}.delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, jvm_buffer_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"direct\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, jvm_buffer_total_capacity{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"direct\"})",
     "legendFormat": "{{instance}}.capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, jvm_buffer_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"direct\"})",
     "legendFormat": "{{instance}}.count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, jvm_buffer_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"mapped\"})",
     "legendFormat": "{{instance}}.used"
    },
    {
     "expr": "topk(10, jvm_buffer_total_capacity{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"mapped\"})",
     "legendFormat": "{{instance}}.capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, jvm_buffer_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", id=\"mapped\"})",
     "legendFormat": "{{instance}}.count"
    }
   ]
  }
 ]
}