{
 "title": "OpenTelemetry Spring Micrometer",
 "tags": [
  "loki",
  "mimir",
  "spring",
  "micrometer",
  "otlp",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "loki_ds", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(jvm_info,service_name)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(jvm_info{service_name=\"$service_name\"},deployment_environment)"
    }
   },
   {
    "name": "service_version",
    "label": "Service version",
    "query": {
     "query": "label_values(jvm_info{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},service_version)"
    }
   },
   {
    "name": "service_instance_id",
    "label": "Service Instance Id",
    "query": {
     "query": "label_values(jvm_info{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},service_instance_id)"
    }
   },
   { "name": "saturation", "query": "50% : 50,80% : 80,90% : 90" },
   {
    "name": "jvm_memory_used_id",
    "label": "JVM Memory used",
    "query": {
     "query": "label_values(jvm_memory_used{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},id)"
    }
   },
   {
    "name": "jvm_buffer_memory_used_id",
    "label": "JVM Buffer Memory used",
    "query": {
     "query": "label_values(jvm_buffer_memory_used{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method,uri,status) (rate(http_server_requests_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, uri, status) (rate(http_server_requests_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\", status!~\"[1-3]..\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Http Server requests Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (status,uri,method) (rate(http_server_requests_sum{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}[1m]))\r\n/\r\nsum by (status,uri,method) (rate(http_server_requests_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}: {{status}}"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "System CPU Usage > ${saturation:text} ",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" of the system the application is running in",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\"}\r\n* 100\r\n> ${saturation:value}",
     "legendFormat": "${service_instance_id}"
    }
   ]
  },
  {
   "title": "Heap used > ${saturation:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})\r\n* 100 /\r\nsum (jvm_memory_max{service_name=\"${service_name}\", service_instance_id=\"${service_instance_id}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}) \r\n> ${saturation:value}",
     "legendFormat": "${service_instance_id}"
    }
   ]
  },
  {
   "title": "Non-Heap used > ${saturation:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\", area=\"nonheap\"})\r\n* 100 / \r\nsum (jvm_memory_max{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", service_instance_id=\"${service_instance_id}\", area=\"nonheap\"}) \r\n> ${saturation:value}",
     "legendFormat": "${service_instance_id}"
    }
   ]
  },
  {
   "title": "File Descriptors > ${saturation:text}",
   "type": "timeseries",
   "description": "process_files_open_files: The open file descriptor count\n\nprocess_files_max_files: The maximum file descriptor count",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_files_open{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"} \r\n/ \r\nprocess_files_max{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"} \r\n> ${saturation:value}",
     "legendFormat": "{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (jvm_memory_committed{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\",deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum (jvm_memory_max{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})\r\n* 100 /\r\nsum (jvm_memory_max{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})",
       "legendFormat": "${service_instance_id}"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"})\r\n* 100 / \r\nsum (jvm_memory_max{service_name=\"${service_name}\", service_version=\"${service_version}\",  service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"})",
       "legendFormat": "${service_instance_id}"
      }
     ]
    },
    {
     "title": "System CPU Usage",
     "type": "timeseries",
     "description": "The \"recent cpu usage\" of the system the application is running in",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "system.cpu.usage"
      }
     ]
    },
    {
     "title": "Webserver Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_busy{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "tomcat.busy"
      },
      {
       "expr": "topk(10, tomcat_threads_current{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "tomcat.current"
      },
      {
       "expr": "topk(10, tomcat_threads_config_max{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "tomcat.max"
      }
     ]
    },
    {
     "title": "System load",
     "type": "timeseries",
     "description": "https://en.wikipedia.org/wiki/Load_(computing)\n\nFrom micrometer:\n\"The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_load_average_1m{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}\r\n/\r\nsystem_cpu_count{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "load.1m"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "timeseries",
     "description": "jvm_threads_live_threads: The current number of live threads including both daemon and non-daemon threads\n\njvm_threads_daemon_threads: The current number of live daemon threads\n\njvm_threads_peak_threads: The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}.lived"
      },
      {
       "expr": "topk(10, jvm_threads_daemon{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "{{service_instance_id}}.daemon"
      },
      {
       "expr": "topk(10, jvm_threads_peak{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "{{service_instance_id}}.peak"
      }
     ]
    },
    {
     "title": "JVM Threads States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}.{{state}}"
      },
      {
       "expr": "jvm_threads_daemon{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}.daemon"
      },
      {
       "expr": "jvm_threads_peak{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}.peak"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "process_files_open_files: The open file descriptor count\n\nprocess_files_max_files: The maximum file descriptor count",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_files_open{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"} \r\n/ \r\nprocess_files_max{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Logback events",
     "type": "timeseries",
     "description": "logback_events_total: Number of log events that were enabled by the effective log level",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(logback_events{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])",
       "legendFormat": "{{service_instance_id}}.{{level}}"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "description": "jvm_classes_loaded: The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}",
       "legendFormat": "{{service_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_count{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])",
       "legendFormat": "{{service_instance_id}} / {{cause}} / {{gc}} / {{action}}"
      }
     ]
    },
    {
     "title": "Pause duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_sum{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])\r\n/\r\nrate(jvm_gc_pause_count{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])",
       "legendFormat": "{{service_instance_id}} / {{cause}} / {{gc}} / {{action}}"
      }
     ]
    },
    {
     "title": "GC Allocation rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])",
       "legendFormat": "{{service_instance_id}}.allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\"}[1m])",
       "legendFormat": "{{service_instance_id}}.promoted"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "JVM Memory (${jvm_memory_used_id})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "repeat": "jvm_memory_used_id",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", id=\"${jvm_memory_used_id}\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Buffer Memory (${jvm_buffer_memory_used_id})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "repeat": "jvm_buffer_memory_used_id",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used{service_name=\"${service_name}\", service_version=\"${service_version}\", service_instance_id=\"${service_instance_id}\", deployment_environment=\"${deployment_environment}\", id=\"${jvm_buffer_memory_used_id}\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_instance_id=\"$service_instance_id\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}