{
 "title": "Spring Micrometer RED (Top 10)",
 "tags": [
  "loki",
  "mimir",
  "spring",
  "micrometer",
  "otlp",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "loki_ds", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(jvm_info,service_name)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(jvm_info,deployment_environment)"
    }
   },
   { "name": "saturation", "query": "50% : 50,80% : 80,90% : 90" }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id,method,uri,status) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", status=~\"5..\"}[1m])))",
     "legendFormat": "{{method}} {{service_instance_id}}{{uri}}: {{status}}"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap used > ${saturation:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})*100/sum by (service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}) > ${saturation:value})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap used > ${saturation:text}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"})*100/sum by(service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"}) > ${saturation})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"})*100/sum by (service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"heap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id) (jvm_memory_used{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"})*100/sum by(service_instance_id) (jvm_memory_max{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\", area=\"nonheap\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id,method,uri,status) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m])))",
     "legendFormat": "{{method}} {{service_instance_id}}{{uri}}: {{status}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Http Server requests Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service_instance_id,status,uri,method) (rate(http_server_requests_sum{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m]))/sum by (service_instance_id,status,uri,method) (rate(http_server_requests_count{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"}[1m])))",
     "legendFormat": "{{method}} {{service_instance_id}}{{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(process_uptime{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(process_uptime{service_name=\"${service_name}\", deployment_environment=\"${deployment_environment}\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}