# keep version only for graphviz
version: '3.8'
name: otel-lgtm-dotnet
services:
  otelcontribcol-gateway:
    image: otel/opentelemetry-collector-contrib:${OTEL_CONTRIB_COL}
    command: "--config /etc/otelcol-contrib/exporters.yml --config /etc/otelcol-contrib/extensions.yml --config /etc/otelcol-contrib/receivers.yml --config /etc/otelcol-contrib/pipeline.agent.yml --config /etc/otelcol-contrib/pipeline.logs.yml --config /etc/otelcol-contrib/pipeline.metrics.yml --config /etc/otelcol-contrib/pipeline.traces.yml"
    volumes:
      - ./otelcontribcol/gateway/:/etc/otelcol-contrib/:ro
    networks:
      - bridge
    depends_on:
      - mimir
      - loki
      - otelcontribcol-traces-loadbalancer
  otelcontribcol-traces-loadbalancer:
    image: otel/opentelemetry-collector-contrib:${OTEL_CONTRIB_COL}
    command: "--config /etc/otelcol-contrib/exporters.yml --config /etc/otelcol-contrib/extensions.yml --config /etc/otelcol-contrib/pipeline.agent.yml --config /etc/otelcol-contrib/pipeline.traces.yml"
    volumes:
      - ./otelcontribcol/traces-loadbalancer/:/etc/otelcol-contrib/:ro
    networks:
      - bridge
    depends_on:
      - mimir
      - otelcontribcol-traces-collector
  otelcontribcol-traces-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_CONTRIB_COL}
    command: "--config /etc/otelcol-contrib/exporters.yml --config /etc/otelcol-contrib/extensions.yml --config /etc/otelcol-contrib/pipeline.agent.yml --config /etc/otelcol-contrib/pipeline.traces.yml"
    volumes:
      - ./otelcontribcol/traces-collector/:/etc/otelcol-contrib/:ro
    networks:
      - bridge
    depends_on:
      - mimir
      - tempo
    deploy:
      replicas: 2

  curl:
    image: curlimages/curl:8.6.0
    networks:
      - bridge
    entrypoint: sh -c "watch -n 0.1 -d -- /script/curl.sh 2>&1 > /dev/null"
    volumes:
      - ./curl:/script:ro
    depends_on:
      - client
    deploy:
      replicas: 1

  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=persons
      - POSTGRES_PASSWORD=ReallyBadPassword
    networks:
      - bridge

  client:
    build: 
      context: ./client
      dockerfile: ../dotnet.debug.Dockerfile
    environment:
      - SERVICE_NAME=client
      # - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      # - OTEL_TRACES_SAMPLER_ARG=0.1 # demo parameter
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=demo,deployment.environment=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcontribcol-gateway:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_METRIC_EXPORT_INTERVAL=10000
    networks:
      - bridge
    depends_on:
      - service
      - otelcontribcol-gateway
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M

  service:
    build: 
      context: ./service
      dockerfile: ../dotnet.debug.Dockerfile
    environment:
      - SERVICE_NAME=service
      # - OTEL_TRACES_SAMPLER=parentbased_always_on
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=demo,deployment.environment=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcontribcol-gateway:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - FAILURE_RATIO=0.1 # demo parameter
      - LATENCY_RATIO=1 # demo parameter
      - MIN_LATENCY=0 #ms
      - MAX_LATENCY=100 #ms
    networks:
      - bridge
    depends_on:
      - otelcontribcol-gateway
      - db
    deploy:
      # https://github.com/dotnet/runtime/issues/68967
      # https://www.meziantou.net/round-robin-dns-support-in-dotnet-httpclient.htm
      # https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-8.0#configure-grpc-client-side-load-balancing
      replicas: 1
      resources:
        limits:
          memory: 300M

  loki:
    image: grafana/loki@sha256:c59b9e928dffd375920b972e936c81e93bf14114c5229fae56a07cc47b15b475 #main with otlp support https://github.com/grafana/loki/pull/10727
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.11.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml -distributor.otel-metric-suffixes-enabled # otel_metric_suffixes_enabled: https://grafana.com/docs/enterprise-metrics/latest/config/reference/#limits
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.3.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.3.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - loki
      - tempo

networks:
  bridge: